"""The layout rules `DESIGN.md` states, enforced.

A terminal layout breaks quietly: one long file name, one narrow window, and a
line wraps into the next entry's gutter. Nothing raises, the tests stay green,
and the report is unreadable. These tests fail instead.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from filegrail.models import FileRecord, Origin
from filegrail.report import render_text, render_timeline
from filegrail.theme import ARROW, BULLET, FLAG, RAIL, Theme

ROOT = Path("/case")

WIDTHS = [48, 56, 64, 80, 88, 110]


def _record(name: str, origin: Origin | None = None, size: int = 4096) -> FileRecord:
    record = FileRecord(path=f"/case/{name}", size=size, mtime="2026-08-24T19:00:00Z")
    if origin is not None:
        record.origins.append(origin)
    return record


#: One record per evidence class, plus the awkward cases: a very long name, a
#: very long URL, and a file nothing explains.
def _corpus() -> list[FileRecord]:
    return [
        _record(
            "downloads/" + "extremely-long-file-name-" * 6 + ".pdf",
            Origin(
                source="browser-download",
                url="https://example.org/" + "path-segment/" * 12 + "report.pdf",
                referrer="https://example.org/" + "referring-page/" * 8,
                tool="firefox",
                at="2026-08-24T19:02:11Z",
            ),
            size=1 << 30,
        ),
        _record(
            "parser.py",
            Origin(source="archive-member", url="https://example.org/toolkit.zip", tool="chrome"),
        ),
        _record(
            "figure.png",
            Origin(
                source="c2pa",
                tool="OpenAI Media Service API (gpt-image 2.0)",
                note="generated by an AI model; signature not verified",
            ),
        ),
        _record(
            "holiday.jpg",
            Origin(
                source="device-metadata",
                tool="NIKON COOLPIX P6000",
                at="2026-08-22T16:28:39Z",
                geo="43.467448, 11.885127",
            ),
        ),
        _record(
            "export.csv",
            Origin(
                source="shell-history",
                command="curl -o export.csv https://api.example.org/" + "q/" * 30,
                tool="curl",
            ),
        ),
        _record("notes.md"),
        _record("scratch/" + "deeply-nested-directory/" * 5 + "leftover.bin"),
    ]


@pytest.mark.parametrize("width", WIDTHS)
@pytest.mark.parametrize("unicode_ok", [True, False])
def test_no_line_exceeds_the_terminal_width(width: int, unicode_ok: bool):
    theme = Theme(colour=False, unicode=unicode_ok, width=width)

    output = render_text(_corpus(), ROOT, theme=theme, limit=1)

    too_long = [line for line in output.splitlines() if len(line) > width]
    assert not too_long, f"{len(too_long)} line(s) over {width}: {too_long[:1]}"


@pytest.mark.parametrize("width", WIDTHS)
def test_the_timeline_also_stays_inside_the_width(width: int):
    theme = Theme(colour=False, unicode=True, width=width)

    output = render_timeline(_corpus(), ROOT, theme=theme)

    assert not [line for line in output.splitlines() if len(line) > width]


def test_every_entry_line_starts_in_the_gutter():
    """Two spaces, one glyph, one space - and only the glyphs that mean
    something there.

    Measured from the first rule down, which is where the report proper starts.
    Above it is the banner - a wordmark and three labelled rows, none of them an
    entry and none of them in the gutter's language.
    """
    theme = Theme(colour=False, unicode=True, width=88)

    output = render_text(_corpus(), ROOT, theme=theme, limit=0)

    lines = output.splitlines()
    first = next(index for index, line in enumerate(lines) if set(line.strip()) == {"─"})
    body = [line for line in lines[first:] if line[:2] == "  " and line[2:3].strip()]

    gutter = {line[2] for line in body}
    assert gutter <= {BULLET, ARROW, RAIL, FLAG, "─", *"abcdefghijklmnopqrstuvwxyz."}, gutter


def test_headings_appear_only_when_classes_differ():
    theme = Theme(colour=False, unicode=True, width=88)
    one_class = [
        _record("a.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
        _record("b.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
    ]

    output = render_text(one_class, ROOT, theme=theme)

    assert "file metadata" not in output
    assert "Canon EOS 40D" in output


def test_headings_appear_once_a_class_collects_more_than_one_file():
    theme = Theme(colour=False, unicode=True, width=88)
    mixed = [
        _record("a.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
        _record("b.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
        _record("c.pdf", Origin(source="browser-download", url="https://example.org/c.pdf")),
    ]

    output = render_text(mixed, ROOT, theme=theme)

    assert "file metadata" in output
    assert "recorded by another system" in output


def test_no_headings_when_every_class_holds_one_file():
    """A heading over a single entry relabels, it does not group."""
    theme = Theme(colour=False, unicode=True, width=88)
    scattered = [
        _record("a.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
        _record("b.pdf", Origin(source="browser-download", url="https://example.org/b.pdf")),
    ]

    output = render_text(scattered, ROOT, theme=theme)

    assert "file metadata" not in output
    assert "recorded by another system" not in output
    assert "b.pdf" in output


def test_the_strongest_class_is_reported_first():
    """True whether or not headings are shown - the ordering is the point."""
    theme = Theme(colour=False, unicode=True, width=88)
    mixed = [
        _record("a.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
        _record("b.pdf", Origin(source="browser-download", url="https://example.org/b.pdf")),
    ]

    output = render_text(mixed, ROOT, theme=theme)

    assert output.index("b.pdf") < output.index("a.jpg")


# --- the sections that describe the whole scan -------------------------------


def _typed(count: int) -> list[FileRecord]:
    """One file per extension, so the inventory has something to lay out."""
    return [_record(f"file{index}.ext{index}") for index in range(count)]


@pytest.mark.parametrize("width", WIDTHS)
def test_the_inventory_names_every_type_at_every_width(width: int):
    """Columns give way as the terminal narrows. Data never does."""
    output = render_text(_typed(20), ROOT, theme=Theme(colour=False, unicode=True, width=width))

    for index in range(20):
        assert f"EXT{index}" in output, index


def test_the_inventory_drops_a_column_before_it_drops_anything_else():
    def rows(width: int) -> int:
        output = render_text(_typed(20), ROOT, theme=Theme(colour=False, unicode=True, width=width))
        return len([line for line in output.splitlines() if "EXT" in line])

    assert rows(110) < rows(48)


@pytest.mark.parametrize("width", WIDTHS)
@pytest.mark.parametrize("unicode_ok", [True, False])
def test_nothing_in_the_report_ends_in_an_ellipsis(width: int, unicode_ok: bool):
    """`DESIGN.md` says nothing is truncated, and the field names used to be."""
    theme = Theme(colour=False, unicode=unicode_ok, width=width)

    output = render_text(_corpus(), ROOT, theme=theme, limit=0, identify=True)

    assert "…" not in output


def test_the_whole_report_is_ascii_when_the_terminal_is():
    theme = Theme(colour=False, unicode=False, width=88)

    output = render_text(_corpus(), ROOT, theme=theme, limit=0, identify=True)

    assert output.isascii()
