import hashlib
import struct
import zlib
from pathlib import Path

from filegrail.sources.c2pa import read_c2pa_manifest


def _box(box_type: bytes, payload: bytes) -> bytes:
    return struct.pack(">I", len(payload) + 8) + box_type + payload


def _description(content_type: bytes, label: str) -> bytes:
    uuid = content_type + b"\x00\x11\x00\x10\x80\x00\x00\xaa\x008\x9bq"
    return _box(b"jumd", uuid + b"\x03" + label.encode() + b"\x00")


def _manifest(cbor_payload: bytes, assertions: tuple = ()) -> bytes:
    claim = _box(b"jumb", _description(b"c2cl", "c2pa.claim.v2") + _box(b"cbor", cbor_payload))
    body = _description(b"c2pa", "c2pa")
    if assertions:
        store = b"".join(
            _box(b"jumb", _description(b"c2as", label) + _box(b"cbor", payload))
            for label, payload in assertions
        )
        body += _box(b"jumb", _description(b"c2as", "c2pa.assertions") + store)
    return _box(b"jumb", body + claim)


def _cbor(value) -> bytes:
    """Encode the CBOR subset the tests need.

    Hand-written byte literals are encoded by their own length prefix, which is
    exactly the kind of arithmetic a test should not be doing by hand.
    """

    def head(major: int, argument: int) -> bytes:
        if argument < 24:
            return bytes([major << 5 | argument])
        if argument < 0x100:
            return bytes([major << 5 | 24, argument])
        if argument < 0x10000:
            return bytes([major << 5 | 25]) + struct.pack(">H", argument)
        return bytes([major << 5 | 26]) + struct.pack(">I", argument)

    if isinstance(value, Tagged):
        return head(6, value.tag) + _cbor(value.value)
    if isinstance(value, Fixed):
        # Always four bytes, so patching the value cannot resize the manifest.
        return bytes([26]) + struct.pack(">I", value.value)
    if isinstance(value, bytes):
        return head(2, len(value)) + value
    if isinstance(value, str):
        raw = value.encode("utf-8")
        return head(3, len(raw)) + raw
    if isinstance(value, int):
        return head(0, value)
    if isinstance(value, list):
        return head(4, len(value)) + b"".join(_cbor(item) for item in value)
    if isinstance(value, dict):
        return head(5, len(value)) + b"".join(
            _cbor(key) + _cbor(item) for key, item in value.items()
        )
    raise TypeError(value)


class Fixed:
    """A CBOR integer pinned to one width, so a later patch cannot resize it."""

    def __init__(self, value: int) -> None:
        self.value = value


class Tagged:
    def __init__(self, tag: int, value) -> None:
        self.tag = tag
        self.value = value


IPTC = "http://cv.iptc.org/newscodes/digitalsourcetype/"

GENERATED_CLAIM = _cbor(
    {
        "claim_generator_info": {"name": "OpenAI Media Service API"},
        "actions": [
            {
                "action": "c2pa.created",
                "when": Tagged(0, "2026-07-15T00:00:00Z"),
                "softwareAgent": {"name": "gpt-image", "version": "2.0"},
                "digitalSourceType": IPTC + "trainedAlgorithmicMedia",
            }
        ],
    }
)


def _png_with(path: Path, jumbf: bytes) -> tuple[int, int]:
    def chunk(kind: bytes, payload: bytes) -> bytes:
        return (
            struct.pack(">I", len(payload))
            + kind
            + payload
            + struct.pack(">I", zlib.crc32(kind + payload))
        )

    header = b"\x89PNG\r\n\x1a\n" + chunk(b"IHDR", struct.pack(">IIBBBBB", 1, 1, 8, 6, 0, 0, 0))
    manifest_chunk = chunk(b"caBX", jumbf)
    path.write_bytes(header + manifest_chunk + chunk(b"IDAT", b"\x00") + chunk(b"IEND", b""))
    return len(header), len(manifest_chunk)


def test_reads_an_ai_generated_png(tmp_path: Path):
    image = tmp_path / "generated.png"
    _png_with(image, _manifest(GENERATED_CLAIM))

    origin = read_c2pa_manifest(image)

    assert origin is not None
    assert origin.source == "c2pa"
    assert origin.tool == "OpenAI Media Service API (gpt-image 2.0)"
    assert origin.at == "2026-07-15T00:00:00Z"
    assert "generated by an AI model" in origin.note
    assert origin.confidence == 60


def test_always_says_the_signature_was_not_verified(tmp_path: Path):
    image = tmp_path / "generated.png"
    _png_with(image, _manifest(GENERATED_CLAIM))

    assert "signature not verified" in read_c2pa_manifest(image).note


def test_camera_capture_is_labelled_as_such(tmp_path: Path):
    claim = _cbor(
        {"actions": [{"action": "c2pa.created", "digitalSourceType": IPTC + "digitalCapture"}]}
    )
    image = tmp_path / "photo.png"
    _png_with(image, _manifest(claim))

    assert "captured by a camera" in read_c2pa_manifest(image).note


def test_png_without_a_manifest(tmp_path: Path):
    image = tmp_path / "plain.png"
    _png_with(image, b"")
    image.write_bytes(image.read_bytes().replace(b"caBX", b"tEXt"))

    assert read_c2pa_manifest(image) is None


def test_unsupported_suffix_is_skipped(tmp_path: Path):
    document = tmp_path / "notes.txt"
    document.write_text("hello", encoding="utf-8")

    assert read_c2pa_manifest(document) is None


def test_corrupt_manifest_is_not_an_error(tmp_path: Path):
    image = tmp_path / "broken.png"
    _png_with(image, b"\x00\x00\x00\x10jumb" + b"\xff" * 8)

    assert read_c2pa_manifest(image) is None


def test_truncated_box_length_does_not_hang(tmp_path: Path):
    image = tmp_path / "bad-length.png"
    _png_with(image, struct.pack(">I", 0xFFFFFF) + b"jumb" + b"\x00" * 4)

    assert read_c2pa_manifest(image) is None


#: A value that will not occur by accident in the rest of the fixture, so the
#: real digest can be patched in exactly where the placeholder sat.
_PLACEHOLDER = b"\xab" * 32


def _png_with_binding(path: Path, claim: bytes, *, alg: str | None = "sha256") -> None:
    """Write a PNG whose data hash assertion really does cover its own bytes.

    The assertion has to name the range it excludes, and that range is only
    known once the file has been laid out - so the manifest is written twice.
    The exclusion values are pinned to a fixed width and the digest is written
    over a placeholder of its own length, which is what keeps the second pass
    from moving anything the first pass measured.
    """

    def build(start: int, length: int) -> bytes:
        fields = {"exclusions": [{"start": Fixed(start), "length": Fixed(length)}]}
        if alg is not None:
            fields["alg"] = alg
        fields["hash"] = _PLACEHOLDER
        assertion = _cbor(fields)
        return _manifest(claim, (("c2pa.hash.data", assertion),))

    start, length = _png_with(path, build(0, 0))
    _png_with(path, build(start, length))

    raw = bytearray(path.read_bytes())
    digest = hashlib.sha256(bytes(raw[:start]) + bytes(raw[start + length :])).digest()
    at = raw.index(_PLACEHOLDER)
    raw[at : at + len(_PLACEHOLDER)] = digest
    path.write_bytes(bytes(raw))


def test_a_hash_binding_that_matches_the_file_is_reported(tmp_path: Path):
    image = tmp_path / "bound.png"
    _png_with_binding(image, GENERATED_CLAIM)

    assert "hash binding matches" in read_c2pa_manifest(image).note


def test_a_hash_binding_that_does_not_match_the_file_is_reported(tmp_path: Path):
    """The point of the check: a manifest that is not about these bytes."""
    image = tmp_path / "transplanted.png"
    _png_with_binding(image, GENERATED_CLAIM)

    raw = bytearray(image.read_bytes())
    raw[-1] ^= 0xFF  # a byte outside the excluded manifest chunk
    image.write_bytes(bytes(raw))

    assert "hash binding does not match" in read_c2pa_manifest(image).note


def test_a_manifest_without_a_hash_assertion_claims_nothing_about_binding(tmp_path: Path):
    image = tmp_path / "unbound.png"
    _png_with(image, _manifest(GENERATED_CLAIM))

    assert "hash binding" not in read_c2pa_manifest(image).note


def test_a_hash_algorithm_this_cannot_compute_is_not_guessed_at(tmp_path: Path):
    image = tmp_path / "exotic.png"
    _png_with_binding(image, GENERATED_CLAIM, alg="whirlpool")

    assert "hash binding" not in read_c2pa_manifest(image).note


def test_the_hash_algorithm_may_be_inherited_from_the_claim(tmp_path: Path):
    """The specification makes `alg` optional in the assertion when the claim
    already states one, and real manifests leave it out."""
    claim = _cbor(
        {
            "alg": "sha256",
            "claim_generator_info": {"name": "Quiet Tool"},
            "actions": [{"action": "c2pa.created"}],
        }
    )
    image = tmp_path / "inherited.png"
    _png_with_binding(image, claim, alg=None)

    assert "hash binding matches" in read_c2pa_manifest(image).note
