"""The layout rules `docs/DESIGN.md` states, enforced.

A terminal layout breaks quietly: one long file name, one narrow window, and a
line wraps into the next entry's gutter. Nothing raises, the tests stay green,
and the report is unreadable. These tests fail instead.
"""

from __future__ import annotations

from pathlib import Path

import pytest

from filegrail.models import FileRecord, Origin
from filegrail.report import render_text, render_timeline
from filegrail.theme import ARROW, BULLET, FLAG, MIDDOT, RAIL, Theme

ROOT = Path("/case")

WIDTHS = [48, 56, 64, 72, 80, 88, 110]


def _record(name: str, origin: Origin | None = None, size: int = 4096) -> FileRecord:
    record = FileRecord(path=f"/case/{name}", size=size, mtime="2026-08-24T19:00:00Z")
    if origin is not None:
        record.origins.append(origin)
    return record


#: One record per evidence class, plus the awkward cases: a very long name, a
#: very long URL, and a file nothing explains.
def _corpus() -> list[FileRecord]:
    return [
        _record(
            "downloads/" + "extremely-long-file-name-" * 6 + ".pdf",
            Origin(
                source="browser-download",
                url="https://example.org/" + "path-segment/" * 12 + "report.pdf",
                referrer="https://example.org/" + "referring-page/" * 8,
                tool="firefox",
                at="2026-08-24T19:02:11Z",
            ),
            size=1 << 30,
        ),
        _record(
            "parser.py",
            Origin(source="archive-member", url="https://example.org/toolkit.zip", tool="chrome"),
        ),
        _record(
            "figure.png",
            Origin(
                source="c2pa",
                tool="OpenAI Media Service API (gpt-image 2.0)",
                note="generated by an AI model; signature not verified",
            ),
        ),
        _record(
            "holiday.jpg",
            Origin(
                source="device-metadata",
                tool="NIKON COOLPIX P6000",
                at="2026-08-22T16:28:39Z",
                geo="43.467448, 11.885127",
            ),
        ),
        _record(
            "export.csv",
            Origin(
                source="shell-history",
                command="curl -o export.csv https://api.example.org/" + "q/" * 30,
                tool="curl",
            ),
        ),
        _record("notes.md"),
        _record("scratch/" + "deeply-nested-directory/" * 5 + "leftover.bin"),
    ]


@pytest.mark.parametrize("width", WIDTHS)
@pytest.mark.parametrize("unicode_ok", [True, False])
def test_no_line_exceeds_the_terminal_width(width: int, unicode_ok: bool):
    theme = Theme(colour=False, unicode=unicode_ok, width=width)

    output = render_text(_corpus(), ROOT, theme=theme, limit=1)

    too_long = [line for line in output.splitlines() if len(line) > width]
    assert not too_long, f"{len(too_long)} line(s) over {width}: {too_long[:1]}"


@pytest.mark.parametrize("width", WIDTHS)
def test_the_timeline_also_stays_inside_the_width(width: int):
    theme = Theme(colour=False, unicode=True, width=width)

    output = render_timeline(_corpus(), ROOT, theme=theme)

    assert not [line for line in output.splitlines() if len(line) > width]


def test_every_entry_line_starts_in_the_gutter():
    """Two spaces, one glyph, one space - and only the glyphs that mean
    something there.

    Measured from the first rule down, which is where the report proper starts.
    Above it is the banner - a wordmark and three labelled rows, none of them an
    entry and none of them in the gutter's language.
    """
    theme = Theme(colour=False, unicode=True, width=88)

    output = render_text(_corpus(), ROOT, theme=theme, limit=0)

    lines = output.splitlines()
    first = next(index for index, line in enumerate(lines) if set(line.strip()) == {"─"})
    body = [line for line in lines[first:] if line[:2] == "  " and line[2:3].strip()]

    gutter = {line[2] for line in body}
    # Headings start at column two and are upper-cased, so their first letter
    # sits in the gutter column as well.
    letters = "abcdefghijklmnopqrstuvwxyz"
    # MIDDOT marks an index row for a file nothing explains.
    allowed = {BULLET, ARROW, RAIL, FLAG, MIDDOT, "─", ".", *letters, *letters.upper()}
    assert gutter <= allowed, gutter


def test_headings_appear_only_when_classes_differ():
    theme = Theme(colour=False, unicode=True, width=88)
    one_class = [
        _record("a.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
        _record("b.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
    ]

    output = render_text(one_class, ROOT, theme=theme)

    assert "FILE METADATA" not in output
    assert "Canon EOS 40D" in output


def test_headings_appear_once_a_class_collects_more_than_one_file():
    theme = Theme(colour=False, unicode=True, width=88)
    mixed = [
        _record("a.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
        _record("b.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
        _record("c.pdf", Origin(source="browser-download", url="https://example.org/c.pdf")),
    ]

    output = render_text(mixed, ROOT, theme=theme)

    assert "FILE METADATA" in output
    assert "RECORDED BY ANOTHER SYSTEM" in output


def test_no_headings_when_every_class_holds_one_file():
    """A heading over a single entry relabels, it does not group."""
    theme = Theme(colour=False, unicode=True, width=88)
    scattered = [
        _record("a.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
        _record("b.pdf", Origin(source="browser-download", url="https://example.org/b.pdf")),
    ]

    output = render_text(scattered, ROOT, theme=theme)

    assert "FILE METADATA" not in output
    assert "RECORDED BY ANOTHER SYSTEM" not in output
    assert "b.pdf" in output


def test_the_strongest_class_is_reported_first():
    """True whether or not headings are shown - the ordering is the point."""
    theme = Theme(colour=False, unicode=True, width=88)
    mixed = [
        _record("a.jpg", Origin(source="device-metadata", tool="Canon EOS 40D")),
        _record("b.pdf", Origin(source="browser-download", url="https://example.org/b.pdf")),
    ]

    output = render_text(mixed, ROOT, theme=theme)

    # The index is a triage list and has an order of its own; this is a claim
    # about the entries, so it is measured from the section that holds them.
    detail = output.split("FILES IN DETAIL")[1]
    assert detail.index("b.pdf") < detail.index("a.jpg")


# --- the sections that describe the whole scan -------------------------------


def _typed(count: int) -> list[FileRecord]:
    """One file per extension, so the inventory has something to lay out."""
    return [_record(f"file{index}.ext{index}") for index in range(count)]


@pytest.mark.parametrize("width", WIDTHS)
def test_the_inventory_names_every_type_at_every_width(width: int):
    """Columns give way as the terminal narrows. Data never does."""
    output = render_text(_typed(20), ROOT, theme=Theme(colour=False, unicode=True, width=width))

    for index in range(20):
        assert f"EXT{index}" in output, index


def test_the_inventory_drops_a_column_before_it_drops_anything_else():
    def rows(width: int) -> int:
        output = render_text(_typed(20), ROOT, theme=Theme(colour=False, unicode=True, width=width))
        return len([line for line in output.splitlines() if "EXT" in line])

    assert rows(110) < rows(48)


@pytest.mark.parametrize("width", WIDTHS)
@pytest.mark.parametrize("unicode_ok", [True, False])
def test_nothing_in_the_report_ends_in_an_ellipsis(width: int, unicode_ok: bool):
    """`docs/DESIGN.md` says nothing is truncated, and the field names used to be."""
    theme = Theme(colour=False, unicode=unicode_ok, width=width)

    output = render_text(_corpus(), ROOT, theme=theme, limit=0, identify=True)

    assert "…" not in output


def test_the_whole_report_is_ascii_when_the_terminal_is():
    theme = Theme(colour=False, unicode=False, width=88)

    output = render_text(_corpus(), ROOT, theme=theme, limit=0, identify=True)

    assert output.isascii()


# --- what a heading is made of when there is no colour ------------------------


def test_section_headings_are_uppercase_so_they_survive_plain_text():
    """`theme.bold` and `theme.paint` both return the text unchanged when
    colour is off, and colour is off in exactly the case that matters: a report
    redirected to a file. Case and position are the only emphasis left, so the
    headings have to carry it themselves rather than lean on styling."""
    theme = Theme(colour=False, unicode=True, width=88)

    output = render_text(_corpus(), ROOT, theme=theme, identify=True, limit=1)

    assert "\n  INVENTORY" in output
    assert "\n  FINDINGS" in output
    assert "\n  FILES" in output
    assert "\n  inventory" not in output


def test_a_heading_keeps_its_count_beside_it():
    theme = Theme(colour=False, unicode=True, width=88)

    output = render_text(_corpus(), ROOT, theme=theme, limit=1)

    heading = next(line for line in output.splitlines() if line.startswith("  INVENTORY"))
    assert heading.rstrip().endswith("types")


# --- the index ----------------------------------------------------------------


def _mixed() -> list[FileRecord]:
    return [
        _record("holiday.jpg", Origin(source="browser-download", url="https://a.example/h.jpg")),
        _record("report.pdf", Origin(source="document-metadata", block="pdf-info", tool="Word")),
        _record("scratch.bin"),
    ]


def test_the_report_opens_with_one_line_a_file():
    """A report with no index makes the reader scroll the whole thing to learn
    which files are worth opening. One line each answers that first."""
    theme = Theme(colour=False, unicode=True, width=88)

    output = render_text(_mixed(), ROOT, theme=theme)

    index = _index_rows(output)
    assert [line.split()[1] for line in index] == ["holiday.jpg", "report.pdf", "scratch.bin"]


def test_a_file_nothing_explains_carries_its_date_in_the_index():
    """The one thing that section used to add over a bare name, kept."""
    theme = Theme(colour=False, unicode=True, width=88)

    output = render_text(_mixed(), ROOT, theme=theme)

    row = next(line for line in _index_rows(output) if "scratch.bin" in line)
    assert "2026-08-24" in row


def test_the_index_replaces_the_list_of_files_with_nothing_in_them():
    """Two lists of the same files is one list too many."""
    theme = Theme(colour=False, unicode=True, width=88)

    output = render_text(_mixed(), ROOT, theme=theme)

    assert "\n  NO FINDINGS" not in output
    assert "scratch.bin" in output


def test_brief_stops_at_the_index():
    """`--brief` used to print the same report without the decoded fields, which
    is not a triage mode - it is the same length minus the useful part."""
    theme = Theme(colour=False, unicode=True, width=88)

    output = render_text(_mixed(), ROOT, theme=theme, brief=True)

    assert "\n  FILES" in output
    assert "\n  FILES IN DETAIL" not in output
    assert "https://a.example/h.jpg" not in output


def _index_rows(output: str) -> list[str]:
    lines = output.splitlines()
    start = next(i for i, line in enumerate(lines) if line.startswith("  FILES")) + 3
    end = next(i for i, line in enumerate(lines[start:], start) if not line.strip())
    return lines[start:end]


def test_an_entry_names_the_class_of_each_claim_when_there_is_more_than_one():
    """The order was already acquisition, then intrinsic, then interaction -
    and a reader had to know that to read it. Naming them costs three lines and
    turns the report's own thesis from a convention into something legible."""
    theme = Theme(colour=False, unicode=True, width=88)
    record = _record(
        "holiday.jpg",
        Origin(source="browser-download", url="https://a.example/h.jpg"),
    )
    record.origins.append(Origin(source="device-metadata", tool="NIKON COOLPIX P6000"))

    output = render_text([record], ROOT, theme=theme)

    detail = output.split("FILES IN DETAIL")[1]
    assert "ACQUISITION" in detail
    assert "INTRINSIC" in detail
    assert detail.index("ACQUISITION") < detail.index("INTRINSIC")


def test_one_class_needs_no_heading_to_tell_it_from_another():
    """A file whose whole story is its own metadata does not need a heading
    saying so; that is relabelling rather than grouping."""
    theme = Theme(colour=False, unicode=True, width=88)
    record = _record("a.jpg", Origin(source="device-metadata", tool="Canon EOS 40D"))

    output = render_text([record], ROOT, theme=theme)

    assert "INTRINSIC" not in output.split("FILES IN DETAIL")[1]
