"""C2PA Content Credentials.

A C2PA manifest is provenance the file carries about itself: which application
produced it, when, and - increasingly the point - whether it was generated by a
model rather than captured by a camera. It is the strongest self-reported claim
available, and unlike a browser record it survives every copy.

The manifest lives in a JUMBF box (ISO/IEC 19566-5) holding CBOR, embedded in a
PNG `caBX` chunk or a JPEG APP11 segment. Both are walked here with the standard
library, so the tool keeps no runtime dependencies.

**The signature is not verified.** Doing that needs certificate-chain validation
and a crypto library. Everything reported from here is therefore what the
manifest *claims*, and a manifest can be copied onto an unrelated file. It is
recorded as evidence, not as proof, and the reported confidence says so.
"""

from __future__ import annotations

import hashlib
import struct
from pathlib import Path

from ..cbor import CborError, loads
from ..models import Origin

PNG_SUFFIXES = {".png"}
JPEG_SUFFIXES = {".jpg", ".jpeg"}
SUPPORTED_SUFFIXES = PNG_SUFFIXES | JPEG_SUFFIXES

_PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
_PNG_C2PA_CHUNK = b"caBX"
_JPEG_APP11 = 0xEB

_JUMBF_SUPERBOX = b"jumb"
_JUMBF_DESCRIPTION = b"jumd"
_JUMBF_CBOR = b"cbor"

#: The hard binding: a hash over the asset with the manifest's own bytes cut
#: out of it. Checking it needs no key and no trust list - only the file - and
#: it answers a different question from the signature: not "who says so" but
#: "is this manifest even about these bytes".
_DATA_HASH = "c2pa.hash.data"

#: Claim boxes are labelled by version - `c2pa.claim`, `c2pa.claim.v2` - and
#: the claim is where the assertion's hash algorithm is inherited from when the
#: assertion itself leaves it out, which real manifests routinely do.
_CLAIM_PREFIX = "c2pa.claim"

_HASHES = {"sha256": hashlib.sha256, "sha384": hashlib.sha384, "sha512": hashlib.sha512}

#: A megabyte at a time, so a large asset is never held in memory to hash it.
_CHUNK = 1 << 20

_MAX_BOXES = 4096
_MAX_DEPTH = 12

#: IPTC digital source types, mapped to what they mean for a reader.
_SOURCE_TYPES = {
    "trainedAlgorithmicMedia": "generated by an AI model",
    "compositeWithTrainedAlgorithmicMedia": "partly generated by an AI model",
    "algorithmicMedia": "generated by an algorithm",
    "digitalCapture": "captured by a camera",
    "digitalArt": "digital art",
    "composite": "a composite of several sources",
}


def read_c2pa_manifest(path: Path) -> Origin | None:
    """Return what a C2PA manifest claims about the file, if one is present."""
    if path.suffix.lower() not in SUPPORTED_SUFFIXES:
        return None
    try:
        jumbf = _extract_jumbf(path)
    except (OSError, struct.error, ValueError):
        return None
    if not jumbf:
        return None

    payloads: list[tuple[str | None, dict]] = []
    try:
        _walk(jumbf, 0, len(jumbf), 0, payloads)
    except (CborError, struct.error, ValueError):
        return None

    inherited = None
    for label, payload in payloads:
        if label and label.startswith(_CLAIM_PREFIX):
            inherited = payload.get("alg")
            break

    binding = None
    for label, payload in payloads:
        if label == _DATA_HASH:
            binding = _binding(path, payload, inherited)
            break

    return _summarise([payload for _, payload in payloads], binding)


# --- container extraction ----------------------------------------------------


def _extract_jumbf(path: Path) -> bytes:
    with path.open("rb") as handle:
        magic = handle.read(8)
        handle.seek(0)
        if magic.startswith(_PNG_MAGIC):
            return _png_chunk(handle)
        if magic.startswith(b"\xff\xd8"):
            return _jpeg_app11(handle)
    return b""


def _png_chunk(handle) -> bytes:
    handle.seek(len(_PNG_MAGIC))
    while True:
        header = handle.read(8)
        if len(header) < 8:
            return b""
        length, chunk_type = struct.unpack(">I4s", header)
        if chunk_type == _PNG_C2PA_CHUNK:
            return handle.read(length)
        if chunk_type in (b"IDAT", b"IEND"):
            return b""
        handle.seek(length + 4, 1)  # payload plus CRC


def _jpeg_app11(handle) -> bytes:
    """Collect APP11 segments, which carry the manifest split across markers."""
    handle.seek(2)
    parts: list[bytes] = []
    while True:
        marker = handle.read(2)
        if len(marker) < 2 or marker[0] != 0xFF:
            break
        if marker[1] in (0xDA, 0xD9):
            break
        length_bytes = handle.read(2)
        if len(length_bytes) < 2:
            break
        (length,) = struct.unpack(">H", length_bytes)
        payload = handle.read(length - 2)
        # APP11: 'JP', 2-byte box instance, 4-byte packet sequence, then data.
        if marker[1] == _JPEG_APP11 and payload.startswith(b"JP"):
            parts.append(payload[8:])
    return b"".join(parts)


# --- JUMBF ------------------------------------------------------------------


def _walk(
    data: bytes,
    offset: int,
    end: int,
    depth: int,
    found: list[tuple[str | None, dict]],
    label: str | None = None,
) -> None:
    """Collect every decodable CBOR payload, under the label it was filed as.

    A JUMBF superbox describes itself in a `jumd` box before its content, so a
    payload's label is whatever the last description at this level said. That
    is what tells an assertion apart from the claim, and one assertion apart
    from another - which matters here, because only one of them is the hash
    binding and reading it out by shape would be a guess.
    """
    if depth > _MAX_DEPTH:
        return

    boxes = 0
    while offset + 8 <= end and boxes < _MAX_BOXES:
        boxes += 1
        (length,) = struct.unpack(">I", data[offset : offset + 4])
        box_type = data[offset + 4 : offset + 8]
        body = offset + 8

        if length == 0:
            length = end - offset
        elif length == 1:  # extended 64-bit length
            if body + 8 > end:
                return
            (length,) = struct.unpack(">Q", data[body : body + 8])
            body += 8
        if length < 8 or offset + length > end:
            return

        box_end = offset + length
        if box_type == _JUMBF_SUPERBOX:
            _walk(data, body, box_end, depth + 1, found)
        elif box_type == _JUMBF_DESCRIPTION:
            label = _label(data, body, box_end) or label
        elif box_type == _JUMBF_CBOR:
            try:
                value = loads(data[body:box_end])
            except CborError:
                value = None
            if isinstance(value, dict):
                found.append((label, value))
        else:
            pass  # binary payloads: icons, thumbnails, signatures

        offset = box_end


def _label(data: bytes, offset: int, end: int) -> str | None:
    """The label out of a JUMBF description box, where it carries one.

    Sixteen bytes of type UUID, then a byte of toggles whose second bit says
    whether a null-terminated label follows.
    """
    if end - offset < 17 or not data[offset + 16] & 0x02:
        return None
    raw = data[offset + 17 : end]
    stop = raw.find(b"\x00")
    return raw[: stop if stop >= 0 else len(raw)].decode("utf-8", "replace") or None


# --- the hard binding -------------------------------------------------------


def _binding(path: Path, assertion: dict, inherited: object = None) -> str | None:
    """Whether the manifest's own hash still describes the file it sits in.

    This is not the signature. It says nothing about who produced the manifest
    or whether to believe them; it says whether this manifest is about these
    bytes at all. A manifest lifted onto a different image fails here, and so
    does an asset edited after the manifest was written - and both are worth
    knowing without a certificate in sight.
    """
    recorded = assertion.get("hash")
    named = assertion.get("alg") or inherited
    hasher = _HASHES.get(named if isinstance(named, str) else "")
    if not isinstance(recorded, bytes) or not recorded or hasher is None:
        return None  # nothing to compare, or an algorithm this cannot compute

    exclusions = assertion.get("exclusions")
    spans = _spans(exclusions) if exclusions is not None else []
    if spans is None:
        return None

    try:
        computed = _hash_excluding(path, spans, hasher)
    except OSError:
        return None
    if computed is None:
        return None
    return "hash binding matches" if computed == recorded else "hash binding does not match"


def _spans(exclusions: object) -> list[tuple[int, int]] | None:
    """The excluded byte ranges, or None where they cannot be trusted."""
    if not isinstance(exclusions, list):
        return None
    spans: list[tuple[int, int]] = []
    for item in exclusions:
        if not isinstance(item, dict):
            return None
        start, length = item.get("start"), item.get("length")
        if not isinstance(start, int) or not isinstance(length, int):
            return None
        if isinstance(start, bool) or isinstance(length, bool):
            return None
        if start < 0 or length < 0:
            return None
        spans.append((start, start + length))
    spans.sort()
    for (_, first_end), (second_start, _) in zip(spans, spans[1:], strict=False):
        if second_start < first_end:
            return None  # overlapping ranges: the intended coverage is unclear
    return spans


def _hash_excluding(path: Path, spans: list[tuple[int, int]], hasher) -> bytes | None:
    """Hash the file with those byte ranges left out of it."""
    digest = hasher()
    position = 0
    with path.open("rb") as handle:
        for start, stop in spans:
            if start < position:
                return None
            _feed(handle, digest, start - position)
            handle.seek(stop)
            position = stop
        while chunk := handle.read(_CHUNK):
            digest.update(chunk)
    return digest.digest()


def _feed(handle, digest, count: int) -> None:
    while count > 0:
        chunk = handle.read(min(count, _CHUNK))
        if not chunk:
            return
        digest.update(chunk)
        count -= len(chunk)


# --- interpretation ----------------------------------------------------------


def _summarise(claims: list[dict], binding: str | None = None) -> Origin | None:
    generator = None
    software = None
    when = None
    source_type = None

    for claim in claims:
        generator = generator or _generator_name(claim)
        for action in _actions(claim):
            when = when or _string(action.get("when"))
            source_type = source_type or _source_label(action.get("digitalSourceType"))
            software = software or _software_agent(action.get("softwareAgent"))

    tool = generator or software
    if generator and software and software not in generator:
        tool = f"{generator} ({software})"
    if not tool and not when and not source_type:
        return None

    notes = [note for note in (source_type, binding, "signature not verified") if note]
    return Origin(source="c2pa", block="c2pa", tool=tool, at=when, note="; ".join(notes))


def _generator_name(claim: dict) -> str | None:
    info = claim.get("claim_generator_info")
    if isinstance(info, dict):
        name = _string(info.get("name"))
        version = _string(info.get("version"))
        if name:
            return f"{name} {version}".strip() if version else name
    if isinstance(info, list):
        for entry in info:
            if isinstance(entry, dict) and _string(entry.get("name")):
                return _string(entry["name"])
    return _string(claim.get("claim_generator"))


def _actions(claim: dict) -> list[dict]:
    actions = claim.get("actions")
    if isinstance(actions, list):
        return [item for item in actions if isinstance(item, dict)]
    return []


def _software_agent(value: object) -> str | None:
    if isinstance(value, dict):
        name = _string(value.get("name"))
        version = _string(value.get("version"))
        if name:
            return f"{name} {version}".strip() if version else name
        return None
    return _string(value)


def _source_label(value: object) -> str | None:
    text = _string(value)
    if not text:
        return None
    return _SOURCE_TYPES.get(text.rstrip("/").rsplit("/", 1)[-1])


def _string(value: object) -> str | None:
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None
