"""C2PA Content Credentials.

A C2PA manifest is provenance the file carries about itself: which application
produced it, when, and - increasingly the point - whether it was generated by a
model rather than captured by a camera. It is the strongest self-reported claim
available, and unlike a browser record it survives every copy.

The manifest lives in a JUMBF box (ISO/IEC 19566-5) holding CBOR, embedded in a
PNG `caBX` chunk or a JPEG APP11 segment. Both are walked here with the standard
library, so the tool keeps no runtime dependencies.

**The signature is not verified.** Doing that needs certificate-chain validation
and a crypto library. Everything reported from here is therefore what the
manifest *claims*, and a manifest can be copied onto an unrelated file. It is
recorded as evidence, not as proof, and the reported confidence says so.
"""

from __future__ import annotations

import struct
from pathlib import Path

from ..cbor import CborError, loads
from ..models import Origin

PNG_SUFFIXES = {".png"}
JPEG_SUFFIXES = {".jpg", ".jpeg"}
SUPPORTED_SUFFIXES = PNG_SUFFIXES | JPEG_SUFFIXES

_PNG_MAGIC = b"\x89PNG\r\n\x1a\n"
_PNG_C2PA_CHUNK = b"caBX"
_JPEG_APP11 = 0xEB

_JUMBF_SUPERBOX = b"jumb"
_JUMBF_DESCRIPTION = b"jumd"
_JUMBF_CBOR = b"cbor"

_MAX_BOXES = 4096
_MAX_DEPTH = 12

#: IPTC digital source types, mapped to what they mean for a reader.
_SOURCE_TYPES = {
    "trainedAlgorithmicMedia": "generated by an AI model",
    "compositeWithTrainedAlgorithmicMedia": "partly generated by an AI model",
    "algorithmicMedia": "generated by an algorithm",
    "digitalCapture": "captured by a camera",
    "digitalArt": "digital art",
    "composite": "a composite of several sources",
}


def read_c2pa_manifest(path: Path) -> Origin | None:
    """Return what a C2PA manifest claims about the file, if one is present."""
    if path.suffix.lower() not in SUPPORTED_SUFFIXES:
        return None
    try:
        jumbf = _extract_jumbf(path)
    except (OSError, struct.error, ValueError):
        return None
    if not jumbf:
        return None

    claims: list[dict] = []
    try:
        _walk(jumbf, 0, len(jumbf), 0, claims)
    except (CborError, struct.error, ValueError):
        return None

    return _summarise(claims)


# --- container extraction ----------------------------------------------------


def _extract_jumbf(path: Path) -> bytes:
    with path.open("rb") as handle:
        magic = handle.read(8)
        handle.seek(0)
        if magic.startswith(_PNG_MAGIC):
            return _png_chunk(handle)
        if magic.startswith(b"\xff\xd8"):
            return _jpeg_app11(handle)
    return b""


def _png_chunk(handle) -> bytes:
    handle.seek(len(_PNG_MAGIC))
    while True:
        header = handle.read(8)
        if len(header) < 8:
            return b""
        length, chunk_type = struct.unpack(">I4s", header)
        if chunk_type == _PNG_C2PA_CHUNK:
            return handle.read(length)
        if chunk_type in (b"IDAT", b"IEND"):
            return b""
        handle.seek(length + 4, 1)  # payload plus CRC


def _jpeg_app11(handle) -> bytes:
    """Collect APP11 segments, which carry the manifest split across markers."""
    handle.seek(2)
    parts: list[bytes] = []
    while True:
        marker = handle.read(2)
        if len(marker) < 2 or marker[0] != 0xFF:
            break
        if marker[1] in (0xDA, 0xD9):
            break
        length_bytes = handle.read(2)
        if len(length_bytes) < 2:
            break
        (length,) = struct.unpack(">H", length_bytes)
        payload = handle.read(length - 2)
        # APP11: 'JP', 2-byte box instance, 4-byte packet sequence, then data.
        if marker[1] == _JPEG_APP11 and payload.startswith(b"JP"):
            parts.append(payload[8:])
    return b"".join(parts)


# --- JUMBF ------------------------------------------------------------------


def _walk(data: bytes, offset: int, end: int, depth: int, found: list[dict]) -> None:
    """Collect every decodable CBOR payload in the box tree."""
    if depth > _MAX_DEPTH:
        return

    boxes = 0
    while offset + 8 <= end and boxes < _MAX_BOXES:
        boxes += 1
        (length,) = struct.unpack(">I", data[offset : offset + 4])
        box_type = data[offset + 4 : offset + 8]
        body = offset + 8

        if length == 0:
            length = end - offset
        elif length == 1:  # extended 64-bit length
            if body + 8 > end:
                return
            (length,) = struct.unpack(">Q", data[body : body + 8])
            body += 8
        if length < 8 or offset + length > end:
            return

        box_end = offset + length
        if box_type == _JUMBF_SUPERBOX:
            _walk(data, body, box_end, depth + 1, found)
        elif box_type == _JUMBF_CBOR:
            try:
                value = loads(data[body:box_end])
            except CborError:
                value = None
            if isinstance(value, dict):
                found.append(value)
        elif box_type != _JUMBF_DESCRIPTION:
            pass  # binary payloads: icons, thumbnails, signatures

        offset = box_end


# --- interpretation ----------------------------------------------------------


def _summarise(claims: list[dict]) -> Origin | None:
    generator = None
    software = None
    when = None
    source_type = None

    for claim in claims:
        generator = generator or _generator_name(claim)
        for action in _actions(claim):
            when = when or _string(action.get("when"))
            source_type = source_type or _source_label(action.get("digitalSourceType"))
            software = software or _software_agent(action.get("softwareAgent"))

    tool = generator or software
    if generator and software and software not in generator:
        tool = f"{generator} ({software})"
    if not tool and not when and not source_type:
        return None

    notes = [note for note in (source_type, "signature not verified") if note]
    return Origin(source="c2pa", block="c2pa", tool=tool, at=when, note="; ".join(notes))


def _generator_name(claim: dict) -> str | None:
    info = claim.get("claim_generator_info")
    if isinstance(info, dict):
        name = _string(info.get("name"))
        version = _string(info.get("version"))
        if name:
            return f"{name} {version}".strip() if version else name
    if isinstance(info, list):
        for entry in info:
            if isinstance(entry, dict) and _string(entry.get("name")):
                return _string(entry["name"])
    return _string(claim.get("claim_generator"))


def _actions(claim: dict) -> list[dict]:
    actions = claim.get("actions")
    if isinstance(actions, list):
        return [item for item in actions if isinstance(item, dict)]
    return []


def _software_agent(value: object) -> str | None:
    if isinstance(value, dict):
        name = _string(value.get("name"))
        version = _string(value.get("version"))
        if name:
            return f"{name} {version}".strip() if version else name
        return None
    return _string(value)


def _source_label(value: object) -> str | None:
    text = _string(value)
    if not text:
        return None
    return _SOURCE_TYPES.get(text.rstrip("/").rsplit("/", 1)[-1])


def _string(value: object) -> str | None:
    if isinstance(value, str) and value.strip():
        return value.strip()
    return None
